### PR TITLE
Adding the Gaussian Blur feature plus a few minor formatting with gofmt.

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by tariq1890** [comment]
@kirillDanshin @h2non

**Comment by h2non** [comment]
Thanks for the PR. It would be nice if the same options are supported across all endpoints, instead of just `/blur`. You can implement that here:
https://github.com/tariq1890/imaginary/blob/77b5565fb5588b886fa28feab7832d77b69cfe3d/options.go#L42-L66

**Comment by tariq1890** [comment]
@h2non Thanks for the review. I've made the required changes. Let me know if the changes are good to go.

**Comment by h2non** [comment]
Looks good. Just one final thing: can you add the proper query params Markdown documentation across endpoints and global list?

**Comment by tariq1890** [comment]
Done! Let me know if any issues.

**Comment by h2non** [comment]
Thank you!

**Comment by tariq1890** [comment]
Glad to help :)

**Comment by h2non** [comment]
imaginary `v1.0.3` is out!

**Pull request merged**
