### PR TITLE
fix enable-url-source param description in README

### PR DESCRIPTION
**Pull request by nicolasmure**
the desc was the one of the `allowed-origins` param

### CODE REVIEW

**Comment by jbergstroem** [comment]
I feel like the help comment you're adding is removing vital information that was there before (comma separated origins). I'd focus on only changing the start of the sentence!

**Comment by Dynom** [comment]
Frankly I'm inclined to just remove this section. If someone wants to know the supported flags, you could just `docker run --rm -it h2non/imaginary -h`.

However. The documentation update is fine, but the problem lies in the source:
```diff
diff --git imaginary.go imaginary.go
index cb3caa0..eea8fca 100644
--- imaginary.go
+++ imaginary.go
@@ -81,7 +81,7 @@ Options:
   -http-cache-ttl <num>     The TTL in seconds. Adds caching headers to locally served files.
   -http-read-timeout <num>  HTTP read timeout in seconds [default: 30]
   -http-write-timeout <num> HTTP write timeout in seconds [default: 30]
-  -enable-url-source        Restrict remote image source processing to certain origins (separated by commas)
+  -enable-url-source        Enable remote HTTP URL image source processing
   -enable-placeholder       Enable image response placeholder to be used in case of error [default: false]
   -enable-auth-forwarding   Forwards X-Forward-Authorization or Authorization header to the image source server. -enable-url-source flag must be defined. Tip: secure your server from public access to prevent attack vectors
   -enable-url-signature     Enable URL signature (URL-safe Base64-encoded HMAC digest) [default: false]
```

If you apply that patch as well, it becomes consistent with the actual flag and I can merge it.

**Comment by Dynom** [comment]
> I feel like the help comment you're adding is removing vital information that was there before (comma separated origins). I'd focus on only changing the start of the sentence!

It's a boolean flag, the entire description got copied from a completely different flag. A little odd how it got there. It's also a "bug" from 2016 🤷‍♂️ 

I've corrected the README.md as well, I copied the line from the actual flag and added a brief param indication.

**Comment by nicolasmure** [comment]
Actually, I haven't wrote the sentence myself but copied / pasted it from this other section in the readme : https://github.com/h2non/imaginary/blame/master/README.md#L347

Should this be updated too ?

**Comment by Dynom** [comment]
Nah, just merge in my patch and it's good to go.

Feel free to fix other documentation issues though (in a different PR)

**Comment by jbergstroem** [comment]
> It's a boolean flag, the entire description got copied from a completely different flag. A little odd how it got there. It's also a "bug" from 2016 🤷‍♂️

Ah, ouch. Didn't know.

**Comment by Dynom** [comment]
Thanks for your contribution!

**Pull request merged**
