### PR TITLE
Add Docker Compose note to README

### PR DESCRIPTION
**Pull request by tillkruss**
It might be nice to have a ready to go snippet for `docker-compose.yml` files.

It's a minimal example, maybe it would be helpful to show how to mount a local Docker volume as well?

### CODE REVIEW

**Comment by h2non** [comment]
Just use ‘volumes’ directice. I can lrovided a fullfeatured example.

**Comment by tillkruss** [comment]
If you could provide a full example, that would be splendid, I'll add it to the PR.

**Comment by h2non** [comment]
```yaml
version: "3"
services:
  imaginary:
    image: h2non/imaginary:1
    volumes:
      - images:/mnt/data
    environment:
       PORT: 9000
    command: -enable-url-source -mount /mnt/data
    ports:
      - "9000:9000"
    deploy:
      placement:
        constraints: [node.role == manager]
```

**Comment by tillkruss** [comment]
Mhh, there is so many different ways to mount. People could mount an existing application volume, or a dedicated imaginary volume, or even a minio volume. Maybe it's better to keep it simple and extend when necessary?

**Comment by h2non** [comment]
I think that is enough for local/development purposes.

**Pull request merged**
