### PR TITLE
Fixing SSL certificates

### LINKED ISSUE #188: running docker image on mac os x has an issue with certificates
Hi, this was the error I got 
```{"message":"Error downloading image: Get https://somedomain.some/someimage.jpg: x509: failed to load system roots and no roots provided","code":1}```

I fixed it mounting the certs volume, adding these lines to docker-compose.yml file
```
imaginary:
        volumes:
            - /etc/ssl/certs:/etc/ssl/certs
```

I think this will help if this to be in troubleshooting guide - readme or somewhere.

Thanks a lot

### PR DESCRIPTION
**Pull request by Dynom**
This PR effectively reverts #186 and should fix #188 and #185

### CODE REVIEW

**Comment by Dynom** [comment]
The build fails due to compilation problems with [libvips on the master branch](https://travis-ci.org/h2non/imaginary/jobs/353765688), it's unrelated to this PR.

**Comment by h2non** [comment]
Thanks @Dynom.

BTW, since you are a recurrent contributor, if you are interested in being a first-class maintainer, let me know. I definitely need help with this project and I can't do it these days.

**Comment by Dynom** [comment]
I've considered it, but In all honesty I don't have the time to give it the attention it deserves. But I'm trying to give it some love whenever I can :-)

**Comment by h2non** [comment]
Thanks for the answer. It's fine, no problem.

**Pull request merged**
