### PR TITLE
Adding HEALTHCHECK for docker container

### PR DESCRIPTION
**Pull request by ViBiOh**

### CODE REVIEW

**Comment by Dynom** [comment]
Hi @ViBiOh,

Thanks for your time and effort!

I need to ponder this change for a bit as I'm not intimately familiar with the `HEALTHCHECK` directive and it's implications on installations.

I'm interested to learn what this means for Imaginary. Imaginary exposes a health-point that can be externally consumed and the `docker run` command fails if it fails to start the binary. afaik there isn't an in-between state that needs monitoring and the start-time is very short (no need to wait for something long). It sounds like the `HEALTHCHECK` is mostly valuable for multi-process containers (which Imaginary hasn't).

I will brush up on it and will report back later.

**Comment by Dynom** [comment]
Since it's a Dockerfile change, would you mind using `release/next` as a base for your PR? We're currently in the process of a fairly large overhaul of the Docker setup.

https://github.com/h2non/imaginary/tree/release/next

**Comment by jbergstroem** [comment]
I'm generally not a fan of using `curl` for `HEALTHCHECK`. Also, worth mentioning that this is [not in OCI yet](https://github.com/opencontainers/image-spec/issues/749).

**Comment by ViBiOh** [comment]
Hi, I was trying to monitor the appropriate way to check if the service is up and running. If checking the PID 1 is the way, it's ok for me.

I'm using imaginary as a sidecar for a file browser. The port is not exposed and HTTP only accessible from inside the appropriate network.

**Comment by Dynom** [comment]
> Hi, I was trying to monitor the appropriate way to check if the service is up and running. If checking the PID 1 is the way, it's ok for me.
> 
> I'm using imaginary as a sidecar for a file browser. The port is not exposed and HTTP only accessible from inside the appropriate network.

Understandable setup, is it acceptable for your setup to roll your own Dockerfile using:

```Dockerfile
FROM h2non/imaginary:<tag>

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y curl

HEALTHCHECK --retries=10 CMD curl --fail http://localhost:$PORT/health
```

This will provide you with the desired functionality, without forcing everybody to use it. Otherwise everybody else need to roll a similar Dockerfile and reset `HEALTCHECK` to a noop.

**Comment by ViBiOh** [comment]
I've ended using following config in my `docker-compose`

```
    healthcheck:
      test: ["CMD", "ps", "-p", "1", "--no-headers"]
      retries: 10
```

**Pull request closed without merging**
