### PR TITLE
Updated go to 1.5.1 on the Docker image

### PR DESCRIPTION
**Pull request by Dynom**

### CODE REVIEW

**Comment by Dynom** [comment]
The PR became a bit sloppy, if you want I can rebase and offer a new PR with only the resulting diff.

**Comment by h2non** [comment]
I would prefer that if you don't mind.

**Comment by Dynom** [comment]
Hm, throttled switched (recently?) to gopkg. I'll update the middleware ref to reflect thew new import.

**Comment by Dynom** [comment]
Rebased my changes on upstream/develop, should have no more merge problems now.

**Comment by Dynom** [comment]
I've fixed some other things too. They are unrelated to the PR but were required. This should also resolve some other parts of `develop` if you want to make a new build.

**Comment by h2non** [comment]
No worries, go ahead and let me know when you're done.

**Comment by Dynom** [comment]
Done with this branch, proceeding with the actual PR I wanted to work on

**Comment by Dynom** [comment]
A gees. This entire PR makes no frigging sense. My `develop` branch was out-of-date. Thanks Github.. apparently the `develop` branch was behind 55 commits when I forked Imaginary.

**Comment by h2non** [comment]
I see, however there're still some improvements regarding to the Dockerfile that you can merge, I believe. I've updated the develop branch a while ago, but lately all the changes has been done directly in `master`.

**Comment by Dynom** [comment]
Done in #41.

**Pull request closed without merging**
