### PR TITLE
Add URL signature feature

### PR DESCRIPTION
**Pull request by bleleve**
URL signature pull request as discussed in this issue #183.

> The HMAC-SHA256 hash is created by taking the URL path (including the leading /), the request parameters (alphabetically-sorted, excluding the `sign` one and concatenated with & into a string) and the signature salt. The hash is then base64url-encoded.

Example:
`curl -O "http://localhost:8088/crop?width=500&height=400&url=https%3A%2F%2Fraw.githubusercontent.com%2Fh2non%2Fimaginary%2Fmaster%2Ftestdata%2Flarge.jpg&sign=4d89IjMIL_-lD2GM9MYehsWqcAbv8-j275l-M9xnQQw"`

The source URL should be URL encoded !

### CODE REVIEW

**Comment by h2non** [comment]
This looks promising, thanks for taking the time on this.

I made a quick code review, and I'm wondering about how to handle the POSTed images. While I see this feature is more oriented to pull-only requests, if we want to provide consistent support for this the signature won't be very useful in POST cases unless we provide the checksum of the image payload and expose it via URL param (e.g: `checksum=<hash>`).

Opinions?

**Comment by bleleve** [comment]
Yes you are right, combining the URL path, the request parameters and the image checksum should do the trick.

I will take a look as soon as I have a some time (very busy today).

**Comment by h2non** [comment]
Implementing the image check would be an overhead. I'm thinking that a lighter approach should be adopted instead: we could simply verify some consistent EXIF metadata from the input image, such as resolution, orientation. We could also validate the image size en bytes, which is not a very strong mechanism but perhaps enough for this context use cases.

Moreover, this perhaps has not too much sense for an image processing service, but what about supporting timestamp based verification in the HMAC signature? This is a common approach to secure APIs from replay attacks and so on. If any, this should be strictly optional feature.

**Comment by bleleve** [comment]
Don't you think that the signature URL should be restricted to pull requests ? POST ones can be protected by an authorization header.

**Comment by Dynom** [comment]
I tend to agree with @bleleve that the checksum is most valuable for GET requests, since it's hard to `` and send a header with it. I'm aware that that's not the only use-case, but a signed GET request solves (arguably) that particular use-case the most.

I don't think image checksums are too big of an overhead for Imaginary, it's a relative heavy operation anyway. We can (and should if we decide to checksum the file) limit the amount of bytes read or use a light-weight checksum algorithm. And arguably that should be done on GET requests as well (since the origin URL can change contents, especially if they aren't over a secure connection.

The famous consideration: Imaginary is not dealing with personal health data and it's not a bank. We should consider what problem we're trying to solve. Personally I'd love to hear the use-cases people actually use Imaginary for.

Lastly I think that adding something against replays should be optional. It might be very desirable to allow for replays.

**Comment by bleleve** [comment]
With a req/s limit and a cache I don't think that the file checksum is needed with GET requests. In my use case the URL signature is more than enough.

It should also be interesting to add a CLI flag to disable POST requests.

**Comment by Dynom** [comment]
I think you're right. The advantage of performing a file-checksum, over a URL signature is that files can be served from different origins. But that use-case is probably a reach and won't serve the 80% of those who want to use it. However since we don't have any knowledge about how people are using it, it remains a guesstimate.

The advantage to limiting it to the URL/Query signature is that it's a very "cheap" validation to perform, that requires very little disk/network I/O.

I would love for a second opinion from someone from the crypto/security community.

**Comment by h2non** [comment]
Not sure if we are talking about the same thing. Regarding checksums, I'm referring exclusively to the POST payloads. I think we all agree about the GET ones. I don't see a relevant use case for GET based checksums. Indeed, I would avoid that.

My only point is that with this PR we have partial support for requests signature, but we don't provide any of these capabilities to POST requests. I'm fine shipping the feature as it is now, but I would like to provide a more consistent support. We could optionally restrict POST payloads if the user wants a pull-only server.

Opinions? Ideally, we should reach consensus, and I will proceed with the merge.

**Comment by Dynom** [comment]
Slightly unrelated to the discussion: Do the test-features of `/form` still work when the URL signature flags are defined? @bleleve

**Comment by h2non** [comment]
> I'm not sure what problem, sending a checksum with a POST request, solves. Possibly mitm, but that can be solved with exposing Imaginary over a TLS connection. 

Analog to what is defined in `url` or `file` query params, the checksum will identify and sign a single image resource to avoid a third-party actor abuse. MitM attack vectors are clearly out of scope here.

> Or service abuse, but that can be solved with an authorization header.

That's what we have now and it's open to service abuse. If the authorization token is exposed so some client, you're done here. If you have a middleware proxy that injects authorization for server-to-server access, you are still exposed to abuse unless you implement the control mechanism in the proxy layer. I guess that's why we are considering this feature here.

> I vote to merge this PR and enjoy this feature for GET (pull) requests and start a different topic about what to do with POST requests all together if we want to harden that setup more. The PR doesn't feel "unfinished" to me.

I agree, will do that.

> Slightly unrelated to the discussion: Do the test-features of /form still work when the URL signature flags are defined? @bleleve

It should work since we should ignore non-GET requests for the URL signature verification logic. `/form` endpoint is exclusively using the payload based image processing.

**Comment by hug-abacus** [comment]
@bleleve What's the reasoning behind adding a constant user-provided salt to the hmac?
I don't think this adds any additional security or am I missing something?

**Comment by philhug** [comment]
@Dynom I do agree that a salt/nonce would improve security.
But that's not the way it's implemented in the PR.
The salt is constant.
If the salt should add to the security it would need be randomly selected per request.

The reason why I'm raising this is, that it makes configuring more complex (having to configure 2 keys) without actual security gain.

**Comment by Dynom** [comment]
Perhaps I'm misunderstanding. But if we pick a different salt for every request, there needs to be some form of secret-management with the client making the request. This complicates the interface between Imaginary and the client significantly and is the entire point I tried to make with my previous comment.

If it's deterministic, it's "obtainable" if it's non-deterministic it's complicated to manage with clients.

**Comment by philhug** [comment]
@Dynom if we add a salt/nonce, the following would be a very simple client implementation:

```
curl -O "http://localhost:8088/crop?width=500&height=400&url=https%3A%2F%2Fraw.githubusercontent.com%2Fh2non%2Fimaginary%2Fmaster%2Ftestdata%2Flarge.jpg&nonce=16966882-c1f4-4b55-be5c-cace60b8db65&sign=4d89IjMIL_-lD2GM9MYehsWqcAbv8-j275l-M9xnQQw"

Client code would look like this:

// nonce only needs to be unique, not necessarily random
// e.g. can be implemented as a simple counter
// it can also be kept optional if no replay protection is needed
nonce := uuid.NewV4()

signKey  := "4f46feebafc4b5e988f131c4ff8b5997"
urlPath  := "/resize"
urlQuery := "file=image.jpg&height=200&type=jpeg&width=300&nonce=" + nonce

h := hmac.New(sha256.New, []byte(signKey))
h.Write([]byte(urlPath))
h.Write([]byte(urlQuery))
buf := h.Sum(nil)

fmt.Println("sign=" + base64.RawURLEncoding.EncodeToString(buf))

```
Now you'd have the option to filter your requests (e.g. on a proxy in front of imaginary) and limit the number of requests with the same nonce.

Server side, we would just completely drop the salt code.

**Comment by h2non** [comment]
Folks, I have been passively following this and would make some changes on master before pushing the new version. The salt key would be removed in favour of simplicity. I'm busy but will try to find some time next week.

**Comment by bleleve** [comment]
Hi all,

Sorry for the blackout, I was pretty busy last weeks !

About the SALT, indeed it is not essential but adds a little security at low cost. It is concatenated to the message hashed with the key and adds some complexity.

I did not take the time to add a signature bypass for POST requests.

**Comment by philhug** [comment]
@h2non  I created a PR to remove the salt. See #194

**Comment by batiste** [comment]
When you guys are talking about the salt you are talking about signKey?
It is my understanding that is extremely difficult to guess this signKey even with utterly broken hashing algorithm like md5.

So as long as the secret key cannot be found we are in the clear right and totally secure? Finding collisions is mostly useless for this use case?

**Comment by josepowera** [comment]
I'm preparing signature generation code in Java.  Could anyone check signature conversion code in Java and help to update to make it work like in Go. 

https://stackoverflow.com/questions/51259453/hmacsha256-signature-generated-is-different-in-java-than-in-go

**Pull request merged**
