### PR TITLE
Adding remote url wildcard support

### PR DESCRIPTION
**Pull request by Dynom**

### CODE REVIEW

**Comment by Dynom** [comment]
The builds fail for pre Go 1.9 builds, because I'm using [t.Helper()](https://github.com/golang/proposal/blob/master/design/4899-testing-helper.md) [here](https://github.com/h2non/imaginary/pull/219/files#diff-97c5a12da0638c63ef09962c052dc7acR232), which makes debugging failing tests a lot nicer.

**Comment by Dynom** [comment]
@h2non for your scrutiny.

This would implement wild-card domain support for the URL source and closes https://github.com/h2non/imaginary/issues/218.

**Comment by h2non** [comment]
Thanks! Will take a look later this week.

**Comment by Dynom** [comment]
@h2non Got a chance to take a peek already?

**Comment by h2non** [comment]
All good. Thanks!

**Pull request merged**
